benchmarks/refine.py
benchmarks/tests/test_refine.py

This looks like a nasty performance regression, 1000x slowdown from 0.7.5-git to 0.7.7-git, let's see how it looks on the test machine...

Added performance regression test to refine

---

.asv-machine.json
.travis.yml
requirements.txt

This will give PR authors feedback on whether `asv run` works on their branch.

Run asv in test suite.

---

.travis.yml
benchmarks/integrate.py

cf. https://github.com/spacetelescope/asv/issues/296#issuecomment-123493731

Check correctness in teardown in integral benchmark.

---

benchmarks/large_exprs.py

The setup takes a few seconds now and count_ops does too. I may need to reduce
the expression length.
Fixes #23.

Added benchmarks for count_ops and free_symbols.

---

benchmarks/solve.py

Fixed error in setup.

---

benchmarks/physics/mechanics/kane.py

This one had errors too and this should fix that.

Updated the Kane test so it actually works.

---

benchmarks/lambdify.py

Benchmarks lambdify (both creation ~100 ms) and evaluation (~200 us).

Add benchmark of sympy.lambdify (addresses gh-36)

---

benchmarks/core.py

This isn't all of them, just some ones that I need.

Some core benchmarks from sympy/core/benchmarks

---

benchmarks/matrices.py

#51
- Reduce matrix to 5*5
- Make the matrix numeric
It takes 200us on master, and 4ms on sympy 1.1

Reduce matrix size

---

benchmarks/matrices.py

Added benchmarks for matrix powers, one case which works well now and should not be broken and two cases which any matrix multiplication or power optimizations should improve.

added matrix power benchmarks

---

benchmarks/baseline.py

Fix gcd benchmark

---

benchmarks/polygon.py

Continuing on the effort in benchmarking sympy, i started by benchmarking the polygon class in the geometry folder.
The benchmarks currently work with asv and i'm looking to benchmark other classes in the geometry module once i get some feedback on this benchmark.
* benchmarks
* Added polygon class benchmarking.

Added Polygon benchmark

---

benchmarks/solve.py

These benchmarks give better coverage of the performance regression
identified in https://github.com/sympy/sympy/issues/19200

Add benchmarks for cholesky_solve and is_positive_definite

---

benchmarks/core/Arit.py
benchmarks/core/arit.py
benchmarks/core/expand.py

I am adding basic benchmarks based on the sympy test case and refactor the core benchmarks based on the sympy tests and will add other basic benchmarks in later commits and PRs.
Initially, I was confused about adding the benchmarks as I don't know what I should add in the benchmarks that will be useful, so I am following sympy tests.
If anyone has suggestions for adding benchmarks please give here.
Thanks

refactoring the core benchmarks and add arit and expand benchmarks

---

benchmarks/cse.py

Issue https://github.com/sympy/sympy/issues/24696 highlighted that CSE on matrix expressions was extremely slow because terms were eagerly evaluated during the optimisation pass. PR https://github.com/sympy/sympy/issues/24696 implemented a fix that reduces the runtime on this 2x2 example by ~10,000x, even more for larger systems. It's worth adding as a benchmark to avoid performance regressions in the future.

Add new CSE benchmark based on Kalman filter matrix expression

---

.github/workflows/run-benchmarks.yml

Updated the version from 1.11 to 1.12 in the `.github/workflows/run-benchmarks.yml`

Updated the version from 1.11 to 1.12

---

.github/workflows/run-benchmarks.yml
.gitignore
asv.conf.actions.json
asv.conf.json
asv.conf.venv.json
asv.conf.venv.slow.json
benchmarks/cse.py

See https://github.com/sympy/sympy/pull/25625

Fix cse benchmark

---

.gitattributes

Fix: https://github.com/sympy/sympy_benchmarks/issues/96

Enable JSONC Handling for .json Files in Git

---

asv.conf.actions.json
asv.conf.conda.json
asv.conf.conda.slow.json
asv.conf.json
asv.conf.venv.json
asv.conf.venv.slow.json

Reference: https://github.com/sympy/sympy/issues/26239

Fix CI failure in asv 0.6.2

---

benchmarks/matrices.py

See https://github.com/sympy/sympy/pull/19355.

Add block diagonal eigenvalues benchmarks
